### ISSUE TITLE
Shim is no longer working

### ISSUE THREAD

**Issue by e74000** [e74000/e74000.net#2]
The shim is no longer able to add options to the document.

Logs:

```
2023/09/21 15:43:35 Begin building interface...
wasm_exec.js:22 2023/09/21 15:43:35 Discovered element of type RadioElement adding update function...
panic: syscall/js: call of Value.Call on null
goroutine 1 [running]:
syscall/js.Value.Call({{}, 0x7ff8000000000002, 0x0}, {0x5c492, 0xb}, {0x1605cc8, 0x1, 0x1})
C:/Program Files/Go/src/syscall/js/js.go:392 +0x35
github.com/e74000/wshim.Run(0x69398, {0x1605f00, 0x4, 0x4})
C:/Users/name/go/pkg/mod/github.com/e74000/wshim@v0.0.0-20230315161615-fa7a673344ea/shim.go:61 +0x10
main.main()
```

**Comment by e74000** [comment]
Problem is that the shim is loading before the options panel loads, causing the options panel to not be found. Has been fixed in latest wshim commit, now all programs need to be recompiled to use this new version.
